%% LDE iteration w/o figures
% Output: Iteration firing maps, and L1 diff norm
function [LDEEpoOut,L1DiffNorm] = ...
    LDEIterationMain(...
    PixInptCtgr,LDEIni,p,Epoc,...
    C_SS_mean,C_CS_mean,C_IS_mean,...
    C_SC_mean,C_CC_mean,C_IC_mean,...
    C_SI_mean,C_CI_mean,C_II_mean,...
    L4EmeshX,L4ImeshY,LDEFrfunc,varargin)
% specify NHCout
if length(varargin)>0
    N_HCOut = varargin{1};
    NPixX = varargin{2}; 
    NPixY = varargin{3};
    else
    N_HCOut = 4; NPixX = 10; NPixY = 10;
end

LDEItr = cell(Epoc+1,1);LDEItr{1} = LDEIni;
LDEEpoOut = cell(Epoc+1,1); LDEEpoOut{1} = LDEIni;

for Epc = 1:Epoc
    % First do convolution
    LDEUse = LDEItr{Epc};
    L4EUse = C_SS_mean*LDEUse.S + ...%- diag(C_SS_mean).*LDEUse.S + ...
             C_CS_mean*LDEUse.S + ...%- diag(C_CS_mean).*LDEUse.S + ...
             C_IS_mean*LDEUse.S + ...%- diag(C_IS_mean).*LDEUse.S + ...
             C_SC_mean*LDEUse.C + ...%- diag(C_SC_mean).*LDEUse.C + ...
             C_CC_mean*LDEUse.C + ...%- diag(C_CC_mean).*LDEUse.C + ...
             C_IC_mean*LDEUse.C  ;%- diag(C_IC_mean).*LDEUse.C ;
    L4IUse = C_SI_mean*LDEUse.I + ...%- diag(C_SI_mean).*LDEUse.I + ...
             C_CI_mean*LDEUse.I + ...%- diag(C_CI_mean).*LDEUse.I + ...
             C_II_mean*LDEUse.I  ;%- diag(C_II_mean).*LDEUse.I ;
    
    % Need to resymmetrize!!...
    L4EUse = symmHCs(L4EUse,N_HCOut,NPixX,NPixY);
    L4IUse = symmHCs(L4IUse,N_HCOut,NPixX,NPixY);     
         
         % Refer to functions
    LDEOut = struct('S',[],'C',[],'I',[]);
    LDEOut.S = LDEIterFunc(...
        L4EmeshX, L4ImeshY,...
        LDEFrfunc.S.ORT,LDEFrfunc.S.OBL,LDEFrfunc.S.OPT,...
        L4EUse,L4IUse,LDEUse.S,...
        PixInptCtgr);
    %ORTPix,OBLPix,OPTPix,ORTOBLBd_Pix,OPTOBLBd_Pix);
    LDEOut.C = LDEIterFunc(...
        L4EmeshX, L4ImeshY,...
        LDEFrfunc.C.ORT,LDEFrfunc.C.OBL,LDEFrfunc.C.OPT,...
        L4EUse,L4IUse,LDEUse.C,...
        PixInptCtgr);
    % ORTPix,OBLPix,OPTPix,ORTOBLBd_Pix,OPTOBLBd_Pix);
    LDEOut.I = LDEIterFunc(...
        L4EmeshX, L4ImeshY,...
        LDEFrfunc.I.ORT,LDEFrfunc.I.OBL,LDEFrfunc.I.OPT,...
        L4EUse,L4IUse,LDEUse.I,...
        PixInptCtgr);
    %ORTPix,OBLPix,OPTPix,ORTOBLBd_Pix,OPTOBLBd_Pix);
    LDENext = struct(...
        'S',LDEOut.S*p + LDEUse.S*(1-p),...
        'C',LDEOut.C*p + LDEUse.C*(1-p),...
        'I',LDEOut.I*p + LDEUse.I*(1-p));
    LDEItr{Epc+1} = LDENext; LDEEpoOut{Epc+1} = LDEOut;
end

L1DiffNorm = zeros(Epoc,1);
for Epc = 1:Epoc
    L1DiffNorm(Epc) = ...
        mean(abs(LDEEpoOut{Epc}.S-LDEEpoOut{end}.S),'all')+...
        mean(abs(LDEEpoOut{Epc}.C-LDEEpoOut{end}.C),'all')+...
        mean(abs(LDEEpoOut{Epc}.I-LDEEpoOut{end}.I),'all');
end
end